// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhbQANNItLGDVEyXlntaPNit2BWNU-R4c',
    appId: '1:431307992652:web:2a470b6f1482744a104ee9',
    messagingSenderId: '431307992652',
    projectId: 'my-flutter-app-dd46a',
    authDomain: 'my-flutter-app-dd46a.firebaseapp.com',
    storageBucket: 'my-flutter-app-dd46a.firebasestorage.app',
    measurementId: 'G-2SDKWVNMH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwPpYGUjGlwCtnv7REIH3CePxo-R_SLmw',
    appId: '1:431307992652:android:f0d5a3ad0b5f8cbc104ee9',
    messagingSenderId: '431307992652',
    projectId: 'my-flutter-app-dd46a',
    storageBucket: 'my-flutter-app-dd46a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbAmNUiy6r9JZmLGUbdnv6b28e8KVXUEo',
    appId: '1:431307992652:ios:82934fb14f01e32e104ee9',
    messagingSenderId: '431307992652',
    projectId: 'my-flutter-app-dd46a',
    storageBucket: 'my-flutter-app-dd46a.firebasestorage.app',
    iosClientId: '431307992652-ampurb5ail9s5k7v5gc31nmqmt7aoqtj.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbAmNUiy6r9JZmLGUbdnv6b28e8KVXUEo',
    appId: '1:431307992652:ios:82934fb14f01e32e104ee9',
    messagingSenderId: '431307992652',
    projectId: 'my-flutter-app-dd46a',
    storageBucket: 'my-flutter-app-dd46a.firebasestorage.app',
    iosClientId: '431307992652-ampurb5ail9s5k7v5gc31nmqmt7aoqtj.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAui76IV9I1kdNbkI2cK1NckVOcHrruKX0',
    appId: '1:431307992652:web:fd4f2c1d4b5ede4d104ee9',
    messagingSenderId: '431307992652',
    projectId: 'my-flutter-app-dd46a',
    authDomain: 'my-flutter-app-dd46a.firebaseapp.com',
    storageBucket: 'my-flutter-app-dd46a.firebasestorage.app',
    measurementId: 'G-DMGEG3BVNW',
  );
}
